spring:
  application:
    name: bbs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bbs?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10MB
server:
  port: 8080

